### PR TITLE
Use MathProgNLSModel on all models

### PR DESCRIPTION
**Pull request by abelsiqueira**
except mgh07 and mgh35.

### CODE REVIEW

**Comment by dpo** [comment]
There's a lot to review here. How could we check that the problems are the same? Could we compare problems across the new and old branch somehow?

**Comment by abelsiqueira** [comment]
Let me compare [these](https://travis-ci.org/JuliaSmoothOptimizers/NLSProblems.jl/jobs/380457725#L781) values.

**Comment by abelsiqueira** [comment]
Compared the values and some differences appear:
- `hs42` and `hs24` were wrong and should be correct now.
- differences on the `|c|` value are due to changes on how JuMP stores the constraints and using `x == 1` instead of `x - 1 == 0` in some cases.
- `mgh22` has some difference on `Jt*F` (`5.1235e+02` instead of `5.1293e+02`). Rounding error due to different ways the Jacobian is computed? Maybe I missed something.
- `mgh30` has wrong before (`x[3]` instead of `x[2]`).

**Comment by dpo** [comment]
How did you run the comparison? Do you have a script?

**Comment by abelsiqueira** [comment]
No, I only compared https://travis-ci.org/JuliaSmoothOptimizers/NLSProblems.jl/jobs/380457725#L781
and https://travis-ci.org/JuliaSmoothOptimizers/NLSProblems.jl/jobs/380348322#L772,
which are generated by the `test/runtests.jl`, and verified manually what was strange.
I used `vimdiff` to find the differences.

**Comment by dpo** [comment]
Is this good to go then?

**Comment by abelsiqueira** [comment]
Yes

**Comment by dpo** [comment]
Thank you!

**Pull request merged**
