### PR TITLE
Add references for HS and Luksan-Vlcek problems

### LINKED ISSUE #12: README outdated
We need to update the README to list additional problem sources.

### PR DESCRIPTION
**Pull request by abelsiqueira**
Closes #12

### CODE REVIEW

**Comment by dpo** [comment]
Thanks!! Might be good to add links?

**Comment by abelsiqueira** [comment]
Ah, yes.

**Comment by abelsiqueira** [comment]
Done

**Comment by dpo** [comment]
Thank you!

**Pull request merged**
